add option to append slash to link editable
TorqIT/pimcore pull request #56
Opened 2023-03-10 20:30 UTC by cameronfromtorq

Resolves #54 
<img width="897" alt="image" src="https://user-images.githubusercontent.com/105230931/224422032-adfe2f4c-a955-4ece-9267-e9ae7b906a2b.png">

add a slash if the option is checked and not if it isnt.

Note that I didnt go with a url modification function as that would require a backend call the system doesnt perform in this step (the url is generated on frontend only)

2023-03-10 20:32 UTC, lukemacausland approved these changes

2023-03-17 11:53 UTC, kingjia90 requested changes
Thank you!

Just took a quick view, found 2 issues. 

- While it works for the preview in admin interface, it doesn't appear on the frontend (public) 

Needs to add 
```
        if ($this->data['appendslash']){
            $url .= '/';
        }
```
around here, just before the `?` and `#`
https://github.com/TorqIT/pimcore/blob/88fddbcf708ed3aa7a502e04f1a6d1a0e9415f3c/models/Document/Editable/Link.php#L239-L241

- Needs also check the data type Link (data object), it seems not working properly at the moment
![image](https://user-images.githubusercontent.com/6014195/225896659-73636cde-b7ad-400f-924e-8dede7e595fe.png)

2023-03-21 18:21 UTC, kingjia90 commented on models/Document/Editable/Link.php
> +        if ($this->data['appendslash']) {
needs to be a little bit earlier than `if (strlen($this->data['parameters'] ?? '') > 0) {` on line 239 as trailing slash should before `?somepar=123#anchor1`

2023-03-28 12:12 UTC, lukemacausland reviewed
Looks good, we need to make sure we disable / hide the append slash on dataobject link types or update the dataobject logic so that it saves / opens links as expected.

If we were to hide it, we can probably pass in the type to the openLinkEditPanel, and hide the append slash if its a dataobject type.

2023-04-11 16:36 UTC, lukemacausland commented on bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
> +    console.log(callback);
```suggestion
```

2023-04-11 16:40 UTC, lukemacausland approved these changes

2023-04-12 14:02 UTC, closed without merging